version: '2'

services:
  jenkins:
    container_name: jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    image: jenkinsci/blueocean
    restart: unless-stopped

  jenkins-docker:
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 2376:2376
    image: docker:dind
    restart: unless-stopped

networks:
  jenkins:
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs: